import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Slider from "../components/Slider";
import HomeList from "../components/HomeList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>КФУ Ялта</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <Slider />
        <HomeList />
    </div>
  )
}
