import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>HomePage | NextJS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

     <h1>NextJS</h1>
    </div>
  )
}
